### ISSUE TITLE
Sharded indexes

### ISSUE THREAD

**Issue by Jacknq** [mikegoatly/lifti#32]
Hi, 
just a question, 
is there a way or plan to do index sharding, so that index itself is spiltted in different files or memory streams, 
before I search for example 100 000 documents, loading and reading only relevant part of the index in memory?

thanks for good work

**Comment by mikegoatly** [comment]
@Jacknq There's nothing built into the index implicitly and no current plans - it's not something I'd considered to be honest. 

Off the top of my head, the most pragmatic way to do this would be with some sort of wrapper around a `Dictionary` of indexes, each key being a different partition - that's probably something that could be managed outside of the framework itself in the short term.

**Comment by mikegoatly** [comment]
Something like this (completely untested!)

``` csharp
using Lifti;
using Lifti.Serialization.Binary;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

public class ShardedIndex
        {
            private static readonly BinarySerializer<int> serializer = new BinarySerializer<int>();
            private readonly Dictionary<string, FullTextIndex<int>> indexShards = new Dictionary<string, FullTextIndex<int>>();
            private readonly SemaphoreSlim syncObject = new SemaphoreSlim(1);

            public async Task<FullTextIndex<int>> GetIndexAsync(string partitionKey, CancellationToken cancellationToken = default)
            {
                if (!await syncObject.WaitAsync(TimeSpan.FromSeconds(1), cancellationToken))
                {
                    throw new Exception("Timeout waiting for lock");
                }

                try
                {
                    if (!indexShards.TryGetValue(partitionKey, out var index))
                    {
                        // Create the index for this shard
                        index = new FullTextIndexBuilder<int>()
                                // e.g. shard peristance using the partition key as the file name
                                .WithIndexModificationAction(async (idx) =>
                                {
                                    using (var fileStream = File.OpenWrite($"{partitionKey}.dat"))
                                    {
                                        await serializer.SerializeAsync(idx, fileStream);
                                    }
                                })
                                .Build();

                        // Deserialize initial state, if appropriate
                        var serializedFile = new FileInfo($"{partitionKey}.dat");
                        if (serializedFile.Exists)
                        {
                            using (var stream = serializedFile.OpenRead())
                            {
                                await serializer.DeserializeAsync(index, stream);
                            }
                        }

                        // Store the index for the next access
                        indexShards[partitionKey] = index;
                    }

                    return index;
                }
                finally
                {
                    syncObject.Release();
                }
            }
        }
```

There may be a more optimal solution - just food for thought, more than anything.

**Comment by Jacknq** [comment]
Ok, thanks for hints, interesting stuff!

**Comment by h0lg** [comment]
@mikegoatly Thanks for the example! I have a question considering your use of the `SemaphoreSlim`. Is it protecting some internal resource that's not safe for concurrent use, like the `BinarySerializer`? Is it protecting the non-thread-safe `Dictionary`?

> Edit: Disregard below part - I found the error. I was disposing of the index too early. Above question I still have, but purely out of interest.

I'm asking myself this because I'm trying to implement index sharding and run into the following error with version 6.3.0. Keep in mind this may have nothing to do with Lifti and all with how I'm using it. My current implementation tries to share the `FullTextIndexBuilder` and `BinarySerializer` across threads - I see your example creates a new `FullTextIndexBuilder` on the fly.

> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Threading.SemaphoreSlim'.
   at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.SemaphoreSlim.Wait(TimeSpan timeout)
   at Lifti.FullTextIndex'1.PerformWriteLockedAction(Action action) in D:\a\1\s\src\Lifti.Core\FullTextIndex.cs:line 365
   at Lifti.FullTextIndex'1.BeginBatchChange() in D:\a\1\s\src\Lifti.Core\FullTextIndex.cs:line 148

**Comment by mikegoatly** [comment]
Hi @h0lg - it will be to avoid race conditions where multiple threads try to add values to the dictionary, which isn't thread safe. If you know you'll only have one thread it wouldn't be necessary.

**Comment by mikegoatly** [comment]
Regarding the other part of your question, we could do with the index throwing the exception when it has been disposed, rather than the internal semaphore - that would be much clearer! 😊

**Comment by h0lg** [comment]
@mikegoatly Now I got the sharding working and want to order results by [Score](https://mikegoatly.github.io/lifti/docs/searching/search-results/#double-score--get-) I realize I may need to adjust the Scores I receive from searching different shards. A score in one shard may otherwise not be comparable to a score in another.
Do you have a suggestion on how that could be achieved? Or am I misunderstanding how scoring works?

**Comment by mikegoatly** [comment]
@h0lg  I've got a feeling that this example was thrown together before scoring was implemented in the library - the index itself is responsible for keeping track of the statistics that are used to score results that are obtained from it so your observation that the scores will only be relevant to the particular partition is accurate. 

As it currently stands, you're going to have to implement your own version of an `IScorer`. LIFTI uses an implementation of [`IIndexScorerFactory`](https://github.com/mikegoatly/lifti/blob/52e6c48a1ece5f4f227dfbfcd0587f918667b312/src/Lifti.Core/Querying/IIndexScorerFactory.cs) to create the necessary [`IScorer`](https://github.com/mikegoatly/lifti/blob/52e6c48a1ece5f4f227dfbfcd0587f918667b312/src/Lifti.Core/Querying/IScorer.cs) (i.e. the [`OkapiBm25Scorer`](https://github.com/mikegoatly/lifti/blob/52e6c48a1ece5f4f227dfbfcd0587f918667b312/src/Lifti.Core/Querying/OkapiBm25Scorer.cs))

If you want to use a similar scoring mechanism, you'll need to keep track of the index statistics across all partitions and use them while calculating scores, instead of the statistics associated to each individual partition. It's probably a non-trivial task though keeping them all in sync as the partitions are updated...

**Comment by h0lg** [comment]
@mikegoatly I was afraid I might not like your answer, but didn't know an Okapi could look that scary. Index sharding turns out to be a bit of a rat's nest of non-trivial tasks. Thank you for pointing me in the right direction though - and for your continuous work and support 🚀
