### ISSUE TITLE
non English Fuzzy search 

### ISSUE THREAD

**Issue by thenik** [mikegoatly/lifti#48]
Thanks for your library, it looks amazing,
I want to implement it for [psqqq.com](https://psqqq.com) service for products matching 

Find in the file  list of product names
[product_names_samples.csv](https://github.com/mikegoatly/lifti/files/9647814/product_names_samples.csv)

here is my test  code to search 1 productfrom the mentioned file.

```c#
using Lifti;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FullTextSearchTest
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var r = RunAsync();
        }

        static async Task RunAsync()
        {
            var lines = File.ReadAllLines(@"product_names_samples.csv", Encoding.UTF8);

            var index = new FullTextIndexBuilder<int>()
            .WithDefaultTokenization(o => o.WithStemming())
            .WithQueryParser(o => o.AssumeFuzzySearchTerms())
            .Build();

            //var nn = index.DefaultTokenizer.Normalize("720 мм x 20 мкн. x 3000 м., 3\", KDX MATT, шт");

            //index.DefaultTokenizer.
            index.BeginBatchChange();
            //index.DefaultTokenizer.Normalize()

            var idx2line = new Dictionary<int, string>();
            var i = 1;
            foreach (var l in lines)
            {
                idx2line[i] = l;
                if (i % 100 == 0)
                {
                    Console.WriteLine(i);
                    //break;
                }
                await index.AddAsync(i++, l.Trim('"'));
                //index.ad
                //z.
            }
            await index.CommitBatchChangeAsync();
            //Lifti.Querying.QueryParserException: 'Token expected: EndAdjacentTextOperator'

            var sk = "720 мм x 20 мкн. x 3000 м., 3\", KDX MATT, шт";
            sk = "Нож для TFD-550  1 комплект - 4 ножа ((2 шт  90 град, 2 шт  120 град))";
            sk = sk.Replace("\"", "");

            var res = index.Search(sk);
            //var res = index.Search("720 мм");
            //var res = index.Search("?720 ?мм");

            //var res = index.Search();

            Console.WriteLine($"Found: {res.Count()}");

            foreach (var sa in res)
            {
                var l = idx2line[sa.Key];
                Console.WriteLine($"{sa.Score} - {l}");
                //sa.
            }
        }
    }
}

```

Any ideas how to match the best result here?

PS. 
I think that I build query wrong, but do not have idea how to adjust it right way...

**Comment by mikegoatly** [comment]
Hi @thenik!

Word stemming isn't really going to work for you here - it currently only currently supports English. Combining fuzzy matching with stemming can sometimes give surprising results anyway, so I wouldn't really recommend it.

I'm assuming that when you're searching for `720 мм x 20 мкн. x 3000 м., 3\", KDX MATT, шт`, you want to match product names that contain _any_ of those terms?

By default the query parser will treat your query as a LIFTI query, which means two things:

1. Words separated by spaces will be combined with an "AND" , which I suspect isn't what you want
2. You would need to sanitise the user input and strip out lifti query operators

Because of this, the simplest thing to do would be to create you're own query parser to build the query from the user input. It's not that hard to do, and I've a [blog post doing just this](https://www.goatly.net/post/custom-query-parsers-with-lifti/).

For your query, I think you'd need something like this:

``` c#
public class CustomQueryParser : IQueryParser
{
    public IQuery Parse(IIndexedFieldLookup fieldLookup, string queryText, ITokenizer tokenizer)
    {
        var tokens = tokenizer.Process(queryText);
        if (tokens.Count == 0)
        {
            return new Query(EmptyQueryPart.Instance);
        }
		
        // Join all the tokens together with Or operators
        var combined = CombineAll(tokens.Select(x => new FuzzyMatchQueryPart(x.Value)));

        // Compose the final query
        return new Query(combined);
    }

    public static IQueryPart CombineAll(IEnumerable<IQueryPart> queryParts)
    {
        IQueryPart current = null;
        foreach (var queryPart in queryParts)
        {
            if (current == null)
            {
                current = queryPart;
            }
            else
            {
                current = new OrQueryOperator(current, queryPart);
            }
        }

        return current;
    }
}
```

Note that fuzzy matching on those terms is interesting because lifti won't currently differentiate between character classes, i.e. `34` would potentially fuzzy match to `35` or `3M` (It occurs to me now that fuzzy matching on numbers is a special case that _might_ need to be added to the core library)

You can try the code out in this [.NET Fiddle](https://dotnetfiddle.net/p5ntVE).

**Comment by mikegoatly** [comment]
I've just pushed a new release that will make some of that code a bit cleaner - once .NET fiddle picks up the new version of the package, I'll update the sample there, but the custom query parser will effectively become:

``` csharp
public class CustomQueryParser : IQueryParser
{
    public IQuery Parse(IIndexedFieldLookup fieldLookup, string queryText, ITokenizer tokenizer)
    {
        var tokens = tokenizer.Process(queryText);
        if (tokens.Count == 0)
        {
            return Query.Empty;
        }
		
        // Join all the tokens together with Or operators
        var combined = OrQueryOperator.CombineAll(tokens.Select(x => new FuzzyMatchQueryPart(x.Value)));

        // Compose the final query
        return new Query(combined);
    }
}
```

**Comment by mikegoatly** [comment]
@thenik The latest version of LIFTI should make things even easier as I've added a simple query parser that's trivial to configure without the need for a custom `IQueryParser`. The following is conceptually equivalent to the previous sample:

``` csharp
var index = new FullTextIndexBuilder<int>()
      .WithSimpleQueryParser(
        o => o.AssumeFuzzySearchTerms()
              .WithDefaultJoiningOperator(QueryTermJoinOperatorKind.Or))
      .Build();
```

Hope that helps!

**Comment by thenik** [comment]
@mikegoatly wow, thanks! It helped me a lot,  it is great!
