### ISSUE TITLE
Remove dependency on System.Collections.Immutable

### ISSUE THREAD

**Issue by mikegoatly** [mikegoatly/lifti#78]
[ImTools](https://github.com/dadhi/ImTools) looks like it provides almost drop-in replacements for classes like `ImmutableDictionary` that are used very heavily in LIFTI.

According to the benchmarks they will provide a 2x read speed improvement in our scenarios, and a 6x speed improvement for heavily used operations during indexing.

It would be worth experimenting to see if the perf benefits really do play out.

My only concern is that right now the core library only takes a dependency on a MS-supported library - would taking a dependency on another OSS library be off-putting for anyone?

(I've never officially committed to using only Microsoft-led dependencies, it's just a co-incidence that's where the implementation landed)

**Comment by samba2** [comment]
In our team we don't mind bringing in libs as long as they are 'dry-aged' (around for a long time) and have many contributors. Particularly the last one I find important. Otherwise you can get into trouble when the maintainer looses interest. 
So I'd tend to not add the lib as it seems to have only one contributor.

**Comment by mikegoatly** [comment]
I've decided to the `System.Collections.Immutable` dependency completely. I can keep the immutable semantics without leaking `ImmutableDictionary`s everywhere, initial investigations show that perf and memory is unaffected, and in some cases (index deserialization) perf is actually improved.
